plugins:
  - '@trivago/prettier-plugin-sort-imports'
singleQuote: true
semi: true
printWidth: 100
trailingComma: none
importOrder:
  - '^components/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
